In [2]:
print("Hello world")

Hello world


In [3]:
def square(x):
    return x*x

print(square(2), square(3.2), square(5+6j))

4 10.240000000000002 (-11+60j)


In [8]:
nums = [3, 4, "hello", 5+6j, 6, 7]

def apply(fn, data):
    result = []
    for item in data:
        if type(item) in (int, float):
            r = fn(item)
        else:
            r = 0
        result.append(r)
    return result

apply(square, nums)

[9, 16, 0, 0, 36, 49]

In [10]:
users = ["john", "janes", 56, "mary", "eric", "claire"]

def to_upper(x): return x.upper()


def apply(fn, data):
    from numbers import Number
    result = []
    for item in data:
        if isinstance(item, Number):
            r = fn(item)
        else:
            r = 0
        result.append(r)
    return result

apply(to_upper, users)

AttributeError: 'int' object has no attribute 'upper'

In [ ]:
users = ["john", "janes", 56, "mary", "eric", "claire"]

def to_upper(x): return x.upper()


def apply(fn, data):
    result = []
    for item in data:
        if hasattr(item, "__mul__"):
            r = fn(item)
        else:
            r = 0
        result.append(r)
    return result

apply(to_upper, users)

AttributeError: 'int' object has no attribute 'upper'

In [14]:
users = ["john", "janes", 56, "mary", "eric", "claire"]

def to_upper(x): return x.upper()


def apply(fn, data, default=None):
    result = []
    for item in data:
        try:
            r = fn(item)
        except:
            r = default
        result.append(r)
    return result

apply(to_upper, users, "invalid")

['JOHN', 'JANES', 'invalid', 'MARY', 'ERIC', 'CLAIRE']

In [ ]:
a = list(range(10_000))

%timeit 9999 in a

73.6 μs ± 1 μs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [18]:
a = set(range(10_000))

%timeit 9999 in a

30.1 ns ± 0.664 ns per loop (mean ± std. dev. of 7 runs, 10,000,000 loops each)


In [17]:
a = list(range(100_000))

%timeit 99999 in a

755 μs ± 19.7 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [19]:
a = set(range(100_000))

%timeit 99999 in a

31.2 ns ± 0.429 ns per loop (mean ± std. dev. of 7 runs, 10,000,000 loops each)


In [20]:
a = []

In [21]:
%%timeit

for i in range(100):
    a.append(i*i)

5.9 μs ± 790 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [22]:
%%timeit

a = [ i*i for i in range(100) ]

2.62 μs ± 37.4 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [31]:
def testfn(a, b, c):
    d = a*a
    e = b + d
    for i in range(e):
        print("Counting", i)

t = testfn
t(1, 2, 3)
t.__call__(1, 2, 3)


Counting 0
Counting 1
Counting 2
Counting 0
Counting 1
Counting 2


In [26]:
t.__qualname__

'testfn'

In [27]:
t.__code__

<code object testfn at 0x0000027E129C97D0, file "C:\Users\Deskt\AppData\Local\Temp\ipykernel_25036\2671131532.py", line 1>

In [29]:
t.__code__.co_code

b'\x95\x00X\x00-\x05\x00\x00n\x03X\x13-\x00\x00\x00n\x04[\x01\x00\x00\x00\x00\x00\x00\x00\x00U\x045\x01\x00\x00\x00\x00\x00\x00\x13\x00H\x0f\x00\x00n\x05[\x03\x00\x00\x00\x00\x00\x00\x00\x00S\x01U\x055\x02\x00\x00\x00\x00\x00\x00 \x00M\x11\x00\x00\x0b\x00 \x00g\x00'

In [30]:
import dis
dis.disassemble(t.__code__)

  1           RESUME                   0

  2           LOAD_FAST_LOAD_FAST      0 (a, a)
              BINARY_OP                5 (*)
              STORE_FAST               3 (d)

  3           LOAD_FAST_LOAD_FAST     19 (b, d)
              BINARY_OP                0 (+)
              STORE_FAST               4 (e)

  4           LOAD_GLOBAL              1 (range + NULL)
              LOAD_FAST                4 (e)
              CALL                     1
              GET_ITER
      L1:     FOR_ITER                15 (to L2)
              STORE_FAST               5 (i)

  5           LOAD_GLOBAL              3 (print + NULL)
              LOAD_CONST               1 ('Counting')
              LOAD_FAST                5 (i)
              CALL                     2
              POP_TOP
              JUMP_BACKWARD           17 (to L1)

  4   L2:     END_FOR
              POP_TOP
              RETURN_CONST             0 (None)


In [32]:
x = 10
y = 15
z = x + y
z = x.__add__(y)
z

25

In [ ]:
# Useful introspection functions:
hasattr(), getattr(), setattr(), delattr()
dir(), vars(), locals(), globals()




In [35]:
class User: pass

u = User()
u.name = "John"
u.role = "Admin"

In [36]:
vars(u)

{'name': 'John', 'role': 'Admin'}

In [37]:
vars()

{'__name__': '__main__',
 '__doc__': 'Automatically created module for IPython interactive environment',
 '__package__': None,
 '__loader__': None,
 '__spec__': None,
 '__builtin__': <module 'builtins' (built-in)>,
 '__builtins__': <module 'builtins' (built-in)>,
 '_ih': ['',
  'print("Hello world")',
  'print("Hello world")',
  'def square(x):\n    return x*x\n\nprint(square(2), square(3.2), square(5+6j))',
  'square("Hello")',
  'nums = [3, 4, 5, 6, 7]\n\ndef apply(fn, data):\n    result = []\n    for item in data:\n        r = fn(item)\n        result.append(r)\n    return result\n\napply(square, nums)',
  'nums = [3, 4, "hello", 5, 6, 7]\n\ndef apply(fn, data):\n    result = []\n    for item in data:\n        r = fn(item)\n        result.append(r)\n    return result\n\napply(square, nums)',
  'nums = [3, 4, "hello", 5, 6, 7]\n\ndef apply(fn, data):\n    result = []\n    for item in data:\n        if type(item) in (int, float):\n            r = fn(item)\n        else:\n            r

In [38]:
def square(x):
    return x*x

apply(square, [4, 5, 6, 7, 8])

[16, 25, 36, 49, 64]

In [39]:
apply(lambda x: x*x, [4, 5, 6, 7, 8])

[16, 25, 36, 49, 64]

In [40]:
def square(x):
    return x*x


In [43]:
def testfn():
    sqr = square
    result = []
    for i in range(100):
        result.append(sqr(i))
    return result

testfn()

[0,
 1,
 4,
 9,
 16,
 25,
 36,
 49,
 64,
 81,
 100,
 121,
 144,
 169,
 196,
 225,
 256,
 289,
 324,
 361,
 400,
 441,
 484,
 529,
 576,
 625,
 676,
 729,
 784,
 841,
 900,
 961,
 1024,
 1089,
 1156,
 1225,
 1296,
 1369,
 1444,
 1521,
 1600,
 1681,
 1764,
 1849,
 1936,
 2025,
 2116,
 2209,
 2304,
 2401,
 2500,
 2601,
 2704,
 2809,
 2916,
 3025,
 3136,
 3249,
 3364,
 3481,
 3600,
 3721,
 3844,
 3969,
 4096,
 4225,
 4356,
 4489,
 4624,
 4761,
 4900,
 5041,
 5184,
 5329,
 5476,
 5625,
 5776,
 5929,
 6084,
 6241,
 6400,
 6561,
 6724,
 6889,
 7056,
 7225,
 7396,
 7569,
 7744,
 7921,
 8100,
 8281,
 8464,
 8649,
 8836,
 9025,
 9216,
 9409,
 9604,
 9801]

In [44]:
def testfn(fn):
    sqr = fn
    result = []
    for i in range(100):
        result.append(sqr(i))
    return result

testfn(square)

[0,
 1,
 4,
 9,
 16,
 25,
 36,
 49,
 64,
 81,
 100,
 121,
 144,
 169,
 196,
 225,
 256,
 289,
 324,
 361,
 400,
 441,
 484,
 529,
 576,
 625,
 676,
 729,
 784,
 841,
 900,
 961,
 1024,
 1089,
 1156,
 1225,
 1296,
 1369,
 1444,
 1521,
 1600,
 1681,
 1764,
 1849,
 1936,
 2025,
 2116,
 2209,
 2304,
 2401,
 2500,
 2601,
 2704,
 2809,
 2916,
 3025,
 3136,
 3249,
 3364,
 3481,
 3600,
 3721,
 3844,
 3969,
 4096,
 4225,
 4356,
 4489,
 4624,
 4761,
 4900,
 5041,
 5184,
 5329,
 5476,
 5625,
 5776,
 5929,
 6084,
 6241,
 6400,
 6561,
 6724,
 6889,
 7056,
 7225,
 7396,
 7569,
 7744,
 7921,
 8100,
 8281,
 8464,
 8649,
 8836,
 9025,
 9216,
 9409,
 9604,
 9801]

In [52]:
class MathTools:
    __slots__ = 'testdata',

    def __init__(self):
        self.testdata = 100

    def square(self, x):
        return x*x
    
    def testfn(self):
        result = []
        for i in range(10000):
            result.append(self.square(i))


MathTools.__dict__

mappingproxy({'__module__': '__main__',
              '__firstlineno__': 1,
              '__slots__': ('testdata',),
              '__init__': <function __main__.MathTools.__init__(self)>,
              'square': <function __main__.MathTools.square(self, x)>,
              'testfn': <function __main__.MathTools.testfn(self)>,
              '__static_attributes__': ('testdata',),
              'testdata': <member 'testdata' of 'MathTools' objects>,
              '__doc__': None})

In [55]:
a = {"name": "John", "role": "Admin"}
a["place"]

KeyError: 'place'

In [56]:
from collections import defaultdict
d = defaultdict(int, a)
d

defaultdict(int, {'name': 'John', 'role': 'Admin'})

In [59]:
d["city"]

0

In [60]:
d

defaultdict(int, {'name': 'John', 'role': 'Admin', 'city': 0})

In [ ]:
s = "this is a test is a test string with repeated test words test times"

def count_words(data):
    count = {}
    for word in data.split():
        #if word not in count:
        #    count[word] = 0
        #count[word] += 1
        count[word] = count.get(word, 0) + 1
        
    for w, c in count.items():
        print(f"{w}: {c} times")

count_words(s)


this: 1 times
is: 2 times
a: 2 times
test: 4 times
string: 1 times
with: 1 times
repeated: 1 times
words: 1 times
times: 1 times


In [ ]:
s = "this is a test is a test string with repeated test words test times"

from collections import defaultdict
def count_words(data):
    count = defaultdict(int)

    for word in data.split():
        count[word] += 1
            
    for w, c in count.items():
        print(f"{w}: {c} times")

count_words(s)


this: 1 times
is: 2 times
a: 2 times
test: 4 times
string: 1 times
with: 1 times
repeated: 1 times
words: 1 times
times: 1 times


In [62]:
s = "this is a test is a test string with repeated test words test times"

from collections import Counter
def count_words(data):
    count = Counter(data.split())
            
    for w, c in count.items():
        print(f"{w}: {c} times")

count_words(s)


this: 1 times
is: 2 times
a: 2 times
test: 4 times
string: 1 times
with: 1 times
repeated: 1 times
words: 1 times
times: 1 times


In [65]:
s1 = Counter({"temperature": 30, "humidity": 60})
print(s1)

m = Counter({"temperature": -5, "humidity": 10})
print(m)

s1 + m

Counter({'humidity': 60, 'temperature': 30})
Counter({'humidity': 10, 'temperature': -5})


Counter({'humidity': 70, 'temperature': 25})

In [69]:
Counter(s).most_common(3)

[('t', 13), (' ', 13), ('s', 10)]

In [77]:
from collections import namedtuple

Coords = namedtuple("Coords", ("x", "y"))
print(Coords)

c1 = Coords(10, 20)
c2 = Coords(x=5, y=15)
print(c1, c2)
print(c1[0], c2[1], len(c1))
print(c1.x, c1.y, c2.x, c2.y)

<class '__main__.Coords'>
Coords(x=10, y=20) Coords(x=5, y=15)
10 15 2
10 20 5 15


In [80]:
from time import localtime

t = localtime()
t[:3], t.tm_year, t.tm_mon, t.tm_mday

((2025, 8, 11), 2025, 8, 11)

In [86]:
%%timeit
a = [10, 20, 30]
b = [40, 50, 60]
total = 0
for v in a + b:
    total += v

220 ns ± 6.26 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [91]:
%%timeit
import itertools
a = list(range(1000))
b = list(range(1000))

total = 0
for v in itertools.chain(a, b):
    total += v

71.4 μs ± 1.02 μs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [92]:
%%timeit
import itertools
a = list(range(1000))
b = list(range(1000))

total = 0
for v in a + b:
    total += v

67.3 μs ± 1.17 μs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [93]:
a = (10, 20, 30)

for v in itertools.permutations(a, 2):
    print(v)


(10, 20)
(10, 30)
(20, 10)
(20, 30)
(30, 10)
(30, 20)


In [ ]:
import string
chars = string.printable * 8

for v in itertools.permutations(chars, 8):
    print("".join(v))

'0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ!"#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~ \t\n\r\x0b\x0c'

In [3]:
import itertools
a = [10, 20, 30]
b = [40, 50, 60]

for v in itertools.product(a, b):
    print(v)

(10, 40)
(10, 50)
(10, 60)
(20, 40)
(20, 50)
(20, 60)
(30, 40)
(30, 50)
(30, 60)


In [6]:
a = [33, 44, 55, 66, 77, 88]
a = [ x + 1 for x in a ]
a


[34, 45, 56, 67, 78, 89]

In [16]:
import numpy as np

a = np.array([10, 20, 30, 40], dtype=np.uint8)
a += 1
a[0] = 255

In [22]:
print(a, a.sum(), a.prod(), a.cumsum())
a.sum()

[255  21  31  41] 348 6806205 [255 276 307 348]


np.uint64(348)

In [26]:
a = [22, 33, 54, 12, 49, 78, 52, 96, 53, 54, 33, 39]

[ v for v in a if v % 3 == 0 ]

[33, 54, 12, 78, 96, 54, 33, 39]

In [31]:
n = np.array([10, 20, 30, 40])
n[[2, 0, 1]]

array([30, 10, 20])

In [32]:
n = np.array([10, 20, 30, 40])
n[[False, True, True, False]]

array([20, 30])

In [28]:
a = np.array([22, 33, 54, 12, 49, 78, 52, 96, 53, 54, 33, 39])
a % 3 == 0

array([False,  True,  True,  True, False,  True, False,  True, False,
        True,  True,  True])

In [33]:
a = np.array([22, 33, 54, 12, 49, 78, 52, 96, 53, 54, 33, 39])
a[a % 3 == 0]

array([33, 54, 12, 78, 96, 54, 33, 39])

In [37]:
def square(n):
    print(f"Squaring {n}")
    return n*n

a = [10, 20, 30, 40, 50]

b = [ square(v) for v in a ]
print("Processed")
b

Squaring 10
Squaring 20
Squaring 30
Squaring 40
Squaring 50
Processed


[100, 400, 900, 1600, 2500]

In [39]:
def square(n):
    print(f"Squaring {n}")
    return n*n

a = [10, 20, 30, 40, 50]

b =( square(v) for v in a )
print("Processed")
b

for v in b:
    print(v)

Processed
Squaring 10
100
Squaring 20
400
Squaring 30
900
Squaring 40
1600
Squaring 50
2500


In [35]:
a = [10, 20, 30, 40, 50]

b = ( v*v for v in a )
b

<generator object <genexpr> at 0x000001EA9E97B100>